# Generated by Django 4.1.7 on 2023-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='user', max_length=30, unique=True),
        ),
    ]
