# Generated by Django 4.1.7 on 2023-04-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_register_delete_registeration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='User',
        ),
    ]
